name: Pella Auto Renew

on:
  schedule:
    - cron: '15 */12 * * *'
  # 允许手动在 Actions 页面点击运行按钮
  workflow_dispatch:

jobs:
  renew:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 拉取私库代码
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/pla-renew-private
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Node 20 原生支持 fetch

      - name: Run Script
        env:
          ACCOUNT: ${{ secrets.ACCOUNT }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: node index.js
